export const generateRoomCode = (): string => {
  return Math.random().toString(36).substring(2, 8).toUpperCase();
};

export const generateUserId = (): string => {
  return Math.random().toString(36).substring(2, 15);
};

export const exportSummary = (topics: any[], roomCode: string, participants: any[]): string => {
  const discussedTopics = topics.filter(t => t.discussed);
  const skippedTopics = topics.filter(t => !t.discussed && t.votes.length > 0);
  const totalTimeSpent = discussedTopics.reduce((sum, topic) => sum + topic.timeSpent, 0);
  
  let summary = `# Lean Coffee Session Summary\n\n`;
  summary += `**Room Code:** ${roomCode}\n`;
  summary += `**Date:** ${new Date().toLocaleDateString()}\n`;
  summary += `**Time:** ${new Date().toLocaleTimeString()}\n\n`;
  
  // Participants
  summary += `## Participants (${participants.length})\n\n`;
  participants.forEach((participant) => {
    summary += `- ${participant.name}${participant.isHost ? ' (Host)' : ''}\n`;
  });
  summary += `\n`;
  
  // Session Stats
  summary += `## Session Statistics\n\n`;
  summary += `- **Topics Discussed:** ${discussedTopics.length}\n`;
  summary += `- **Topics Skipped:** ${skippedTopics.length}\n`;
  summary += `- **Total Discussion Time:** ${Math.floor(totalTimeSpent / 60)}:${(totalTimeSpent % 60).toString().padStart(2, '0')}\n`;
  summary += `- **Average Time per Topic:** ${discussedTopics.length > 0 ? Math.round(totalTimeSpent / discussedTopics.length) : 0} seconds\n\n`;
  
  if (discussedTopics.length > 0) {
    summary += `## Discussed Topics\n\n`;
    discussedTopics.forEach((topic, index) => {
      const minutes = Math.floor(topic.timeSpent / 60);
      const seconds = topic.timeSpent % 60;
      summary += `### ${index + 1}. ${topic.text}\n\n`;
      summary += `**Author:** ${topic.authorName}\n`;
      summary += `**Votes:** ${topic.votes.length}\n`;
      summary += `**Time Spent:** ${minutes}:${seconds.toString().padStart(2, '0')}\n\n`;
      if (topic.takeaways && topic.takeaways.trim()) {
        summary += `**Key Takeaways & Next Steps:**\n`;
        summary += `${topic.takeaways}\n\n`;
      }
      summary += `---\n\n`;
    });
  }
  
  if (skippedTopics.length > 0) {
    summary += `## Topics Not Discussed\n\n`;
    summary += `*Consider these topics for your next Lean Coffee session:*\n\n`;
    skippedTopics.forEach((topic, index) => {
      summary += `${index + 1}. **${topic.text}** (${topic.votes.length} votes) - by ${topic.authorName}\n`;
    });
    summary += `\n`;
  }
  
  summary += `---\n\n`;
  summary += `*Generated by Lean Coffee App on ${new Date().toLocaleString()}*\n`;
  
  return summary;
};